import type { Metadata } from "next";
import StoreProvider from "./StoreProvider";
import PageAnimation from "./page-animation";
import PageTop from "./page-top";
import PageMain from "./page-main";
import PageEnd from "./page-end";

// import { Inter } from "next/font/google";
import "./sass/main.sass";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <head>
          <meta charSet="UTF-8"/>
          <title>ItD3VBox</title>
          <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
          <link rel="icon" type="image/png" sizes="192x192" href="/favicon/android-chrome-192x192.png"/>
          <link rel="icon" type="image/png" sizes="512x512" href="/favicon/android-chrome-512x512.png"/>
          <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-16x16.png"/>
          <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-32x32.png"/>
          <link rel="icon" type="image/x-icon" sizes="16x16" href="/favicon/favicon.ico"/>
          <link rel="manifest" href="/favicon/site.webmanifest"/>
        </head>
        <body>
          {/* <PageAnimation /> */}
          <PageTop />
          <PageMain>{ children }</PageMain>
          <PageEnd />
        </body>
      </html>
    </StoreProvider>
  );
}
